### ISSUE TITLE
turf 0.9.4 fails to build on windows 11

### ISSUE THREAD

**Issue by klownie** [myFavShrimp/turf#27]
When i update to 0.9.4 it fails to build on Windows 11.
When i downgrade to 0.9.3, the error persists even tho it didn't before.
```rust
error[E0433]: failed to resolve: could not find `unix` in `os`                                                                                                                                                                                                                                                                                                                       
  --> C:\Users\klownie\.cargo\registry\src\index.crates.io-6f17d22bba15001f\filesystem-hashing-0.3.4\src\hasher.rs:8:14
   |
8  | use std::os::unix::fs::MetadataExt;
   |              ^^^^ could not find `unix` in `os`
   |
note: found an item that was configured out
  --> C:\Users\klownie\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\std\src\os\mod.rs:36:9
   |
36 | pub mod unix {}
   |         ^^^^
note: the item is gated here
  --> C:\Users\klownie\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\std\src\os\mod.rs:28:1
   |
28 | / #[cfg(all(
29 | |     doc,
30 | |     any(
31 | |         all(target_arch = "wasm32", not(target_os = "wasi")),
32 | |         all(target_vendor = "fortanix", target_env = "sgx")
33 | |     )
34 | | ))]
   | |___^
note: found an item that was configured out
  --> C:\Users\klownie\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\std\src\os\mod.rs:85:9
   |
85 | pub mod unix;
   |         ^^^^
note: the item is gated here
  --> C:\Users\klownie\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\std\src\os\mod.rs:84:1
   |
84 | #[cfg(all(not(target_os = "hermit"), any(unix, doc)))]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

   Compiling askama_axum v0.4.0                                                                                                                                                                                                                                                                                                                                                      
error[E0599]: no method named `size` found for struct `Metadata` in the current scope                                                                                                                                                                                                                                                                                                
  --> C:\Users\klownie\.cargo\registry\src\index.crates.io-6f17d22bba15001f\filesystem-hashing-0.3.4\src\hasher.rs:74:25
   |
74 |         size = metadata.size();
   |                         ^^^^ method not found in `Metadata`

error[E0599]: no method named `ctime` found for struct `Metadata` in the current scope                                                                                                                                                                                                                                                                                               
  --> C:\Users\klownie\.cargo\registry\src\index.crates.io-6f17d22bba15001f\filesystem-hashing-0.3.4\src\hasher.rs:75:26
   |
75 |         ctime = metadata.ctime();
   |                          ^^^^^ method not found in `Metadata`

error[E0599]: no method named `mtime` found for struct `Metadata` in the current scope
  --> C:\Users\klownie\.cargo\registry\src\index.crates.io-6f17d22bba15001f\filesystem-hashing-0.3.4\src\hasher.rs:76:26
   |
76 |         mtime = metadata.mtime();
   |                          ^^^^^ method not found in `Metadata`

error[E0599]: no method named `ino` found for struct `Metadata` in the current scope
  --> C:\Users\klownie\.cargo\registry\src\index.crates.io-6f17d22bba15001f\filesystem-hashing-0.3.4\src\hasher.rs:77:24
   |
77 |         ino = metadata.ino();
   |                        ^^^
   |
help: there is a method `into` with a similar name
   |
77 |         ino = metadata.into();
   |                        ~~~~

Some errors have detailed explanations: E0433, E0599.                                                                                                                                                                                                                                                                                                                                
For more information about an error, try `rustc --explain E0433`.
error: could not compile `filesystem-hashing` (lib) due to 5 previous errors
warning: build failed, waiting for other jobs to finish...
```

**Comment by myFavShrimp** [comment]
Thank you for reporting the issue. I will look into this in the next few days

**Comment by myFavShrimp** [comment]
This was a regression that was introduced in `0.9.4` and should be fixed with the new release `0.9.5` that I just created. I hope your issue is resolved now. Thanks again for reporting the problem!
